### PR TITLE
Added project idea

### PR DESCRIPTION
**Pull request by orama254**
Added a project idea about a desktop pacer for speedreading

### CODE REVIEW

**Comment by itaditya** [comment]
Hey @orama254 thanks for volunteering. Can you make the project idea more descriptive?

**Comment by orama254** [comment]
Hey @itaditya sure thing,

The concept is about making a reading pacer(visual guide to direct the reading speed)...like the physical one into a desktop version that can be used to speed read PDFs and e-books on your computer. This can be by either triggering the mouse cursor to change or detecting a PDF or e-book being opened for reading, GUIDING RESOURCE:(https://www.youtube.com/watch?v=H7h5lVSCRm4)

**Comment by itaditya** [comment]
Oh I get it, can you link the video in the README as well.

**Comment by orama254** [comment]
Done

**Comment by itaditya** [comment]
Merged! Congrats

**Pull request merged**
